---
- hosts: splk-index01
  tasks:
    - name: copying Avamar rpm file from DCPOPSAUTOVM01 to target machines
      copy:
        src: files/AvamarClient-linux-sles11-x86_64-19.4.100-116.rpm
        dest: /tmp/
        owner: root
        group: root
        mode: 0644

    - name: install Avamar package on the servers
      yum: 
        name: /tmp/AvamarClient-linux-sles11-x86_64-19.4.100-116.rpm
        state: present

    - name: Start avamar service
      shell: systemctl restart avagent
