---
- hosts: all 
  tasks:
    - name: remove htop package on the server
      yum:
        name: htop
        state: remove

    - name: copying xyz rpm file from master server to target machines
      copy:
        src: xyz_latest.rpm
        dest: /tmp/xyz_latest.rpm
        owner: root
        group: root
        mode: 0644

    - name: install xyz_latest package on the servers
      yum: 
        name: /tmp/xyz_latest.rpm
        state: present
